# .github/workflows/citypulse-deploy.yml
name: citypulse-deploy
on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write          # indispensable pour obtenir le jeton OIDC

jobs:
  publier:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v7.0.1
      - id: auth
        uses: google-github-actions/auth@v3.0.0
        with:
          project_id: poei-formation-gcp
          workload_identity_provider: projects/188463848700/locations/global/workloadIdentityPools/citypulse-ci-hha/providers/forge-principale-hha
          service_account: citypulse-deploy-sa@poei-formation-gcp.iam.gserviceaccount.com

      - uses: google-github-actions/setup-gcloud@v3.0.1
      - name: ecrire un artefact de test
        run: |
          echo "build $GITHUB_RUN_ID" > artefact.txt
          gcloud storage cp artefact.txt gs://citypulse-raw-hha/
